swagger: '2.0'
info:
  title: Web API Skeleton
  description: Skeleton for Dropwizard Web APIs
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - http
basePath: /api/v0
consumes:
  - text/plain
produces:
  - text/plain
paths:
  /getSpendingAuthorit:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - in: "query"
          name: onid
          required: true
          type: string
      responses:
        200:
          description: "request recived"
          schema:
            $ref: '#/definitions/response'
        400:
          description: "onid query parameter is required"
          schema:
            $ref: '#/definitions/Error'
        500:
          description: "internal server error"
          schema:
            $ref: '#/definitions/Error'

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  response:
    type: object
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        $ref: "#/definitions/UserData"

  Links:
    type: object

  UserData:
    type: object
    properties:
      id:
        type: string
        example: "kuok"
      type:
        type: string
        example: "spendingauthority"
      attributes:
        $ref: "#/definitions/LimitsArray"
      links:
        type: string

  LimitsArray:
    type: object
    properties:
      limits:
        type: array
        items:
          $ref: "#/definitions/LimitsInfo"

  LimitsInfo:
    type: object
    properties:
      spendingLimit:
        type: string
        example: "149999.99"
        description: "the spending limit"
      indexes:
        type: array
        items:
          type: string
          example: "JIS261"

  Error:
    properties:
      status:
        type: string
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: string
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
